#!/usr/bin/env python

from sys import argv
from os import system

locals = {}
file_name = None
pyrc = None

if len(argv) > 1:
    file_name = argv[1]
    if file_name.endswith('.pickle'):
        import pickle
        locals.update(pickle.load(open(file_name)))
    else:
        pyrc = file_name

from cixar.ish.pysh.application import run
run(
    port = 2380,
    ssl = True,
    locals = locals,
    pyrc = pyrc,
    interface = 'localhost'
)

